export const images = [
  {
    image: "/images/background1.jpg",
  },
  {
    image: "/images/background2.jpg",
  },
  {
    image: "/images/background3.jpg",
  },
  {
    image: "/images/background4.jpg",
  },
  {
    image: "/images/background5.jpg",
  },
  {
    image: "/images/background6.jpg",
  },
  {
    image: "/images/background8.jpg",
  },
];

export const COLORS = [
  "#fafaf9",
  "#e7e5e4",
  "#d6d3d1",
  "#a8a29e",
  "#78716c",
  "#57534e",
  "#44403c",
  "#292524",
  "#1c1917",
  "#0c0a09",
  "#000",
];

export const days = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const currency_list = [
  { name: "Afghan Afghani", code: "AFA", symbol: "؋" },
  { name: "Albanian Lek", code: "ALL", symbol: "Lek" },
  { name: "Algerian Dinar", code: "DZD", symbol: "دج" },
  { name: "Angolan Kwanza", code: "AOA", symbol: "Kz" },
  { name: "Argentine Peso", code: "ARS", symbol: "$" },
  { name: "Armenian Dram", code: "AMD", symbol: "֏" },
  { name: "Aruban Florin", code: "AWG", symbol: "ƒ" },
  { name: "Australian Dollar", code: "AUD", symbol: "$" },
  { name: "Azerbaijani Manat", code: "AZN", symbol: "m" },
  { name: "Bahamian Dollar", code: "BSD", symbol: "B$" },
  { name: "Bahraini Dinar", code: "BHD", symbol: ".د.ب" },
  { name: "Bangladeshi Taka", code: "BDT", symbol: "৳" },
  { name: "Barbadian Dollar", code: "BBD", symbol: "Bds$" },
  { name: "Belarusian Ruble", code: "BYR", symbol: "Br" },
  { name: "Belgian Franc", code: "BEF", symbol: "fr" },
  { name: "Belize Dollar", code: "BZD", symbol: "$" },
  { name: "Bermudan Dollar", code: "BMD", symbol: "$" },
  { name: "Bhutanese Ngultrum", code: "BTN", symbol: "Nu." },
  { name: "Bitcoin", code: "BTC", symbol: "฿" },
  { name: "Bolivian Boliviano", code: "BOB", symbol: "Bs." },
  { name: "Bosnia-Herzegovina Convertible Mark", code: "BAM", symbol: "KM" },
  { name: "Botswanan Pula", code: "BWP", symbol: "P" },
  { name: "Brazilian Real", code: "BRL", symbol: "R$" },
  { name: "British Pound Sterling", code: "GBP", symbol: "£" },
  { name: "Brunei Dollar", code: "BND", symbol: "B$" },
  { name: "Bulgarian Lev", code: "BGN", symbol: "Лв." },
  { name: "Burundian Franc", code: "BIF", symbol: "FBu" },
  { name: "Cambodian Riel", code: "KHR", symbol: "KHR" },
  { name: "Canadian Dollar", code: "CAD", symbol: "$" },
  { name: "Cape Verdean Escudo", code: "CVE", symbol: "$" },
  { name: "Cayman Islands Dollar", code: "KYD", symbol: "$" },
  { name: "CFA Franc BCEAO", code: "XOF", symbol: "CFA" },
  { name: "CFA Franc BEAC", code: "XAF", symbol: "FCFA" },
  { name: "CFP Franc", code: "XPF", symbol: "₣" },
  { name: "Chilean Peso", code: "CLP", symbol: "$" },
  { name: "Chilean Unit of Account", code: "CLF", symbol: "CLF" },
  { name: "Chinese Yuan", code: "CNY", symbol: "¥" },
  { name: "Colombian Peso", code: "COP", symbol: "$" },
  { name: "Comorian Franc", code: "KMF", symbol: "CF" },
  { name: "Congolese Franc", code: "CDF", symbol: "FC" },
  { name: "Costa Rican Colón", code: "CRC", symbol: "₡" },
  { name: "Croatian Kuna", code: "HRK", symbol: "kn" },
  { name: "Cuban Convertible Peso", code: "CUC", symbol: "$, CUC" },
  { name: "Czech Republic Koruna", code: "CZK", symbol: "Kč" },
  { name: "Danish Krone", code: "DKK", symbol: "Kr." },
  { name: "Djiboutian Franc", code: "DJF", symbol: "Fdj" },
  { name: "Dominican Peso", code: "DOP", symbol: "$" },
  { name: "East Caribbean Dollar", code: "XCD", symbol: "$" },
  { name: "Egyptian Pound", code: "EGP", symbol: "ج.م" },
  { name: "Eritrean Nakfa", code: "ERN", symbol: "Nfk" },
  { name: "Estonian Kroon", code: "EEK", symbol: "kr" },
  { name: "Ethiopian Birr", code: "ETB", symbol: "Nkf" },
  { name: "Euro", code: "EUR", symbol: "€" },
  { name: "Falkland Islands Pound", code: "FKP", symbol: "£" },
  { name: "Fijian Dollar", code: "FJD", symbol: "FJ$" },
  { name: "Gambian Dalasi", code: "GMD", symbol: "D" },
  { name: "Georgian Lari", code: "GEL", symbol: "ლ" },
  { name: "German Mark", code: "DEM", symbol: "DM" },
  { name: "Ghanaian Cedi", code: "GHS", symbol: "GH₵" },
  { name: "Gibraltar Pound", code: "GIP", symbol: "£" },
  { name: "Greek Drachma", code: "GRD", symbol: "₯, Δρχ, Δρ" },
  { name: "Guatemalan Quetzal", code: "GTQ", symbol: "Q" },
  { name: "Guinean Franc", code: "GNF", symbol: "FG" },
  { name: "Guyanaese Dollar", code: "GYD", symbol: "$" },
  { name: "Haitian Gourde", code: "HTG", symbol: "G" },
  { name: "Honduran Lempira", code: "HNL", symbol: "L" },
  { name: "Hong Kong Dollar", code: "HKD", symbol: "$" },
  { name: "Hungarian Forint", code: "HUF", symbol: "Ft" },
  { name: "Icelandic Króna", code: "ISK", symbol: "kr" },
  { name: "Indian Rupee", code: "INR", symbol: "₹" },
  { name: "Indonesian Rupiah", code: "IDR", symbol: "Rp" },
  { name: "Iranian Rial", code: "IRR", symbol: "﷼" },
  { name: "Iraqi Dinar", code: "IQD", symbol: "د.ع" },
  { name: "Israeli New Sheqel", code: "ILS", symbol: "₪" },
  { name: "Italian Lira", code: "ITL", symbol: "L,£" },
  { name: "Jamaican Dollar", code: "JMD", symbol: "J$" },
  { name: "Japanese Yen", code: "JPY", symbol: "¥" },
  { name: "Jordanian Dinar", code: "JOD", symbol: "ا.د" },
  { name: "Kazakhstani Tenge", code: "KZT", symbol: "лв" },
  { name: "Kenyan Shilling", code: "KES", symbol: "KSh" },
  { name: "Kuwaiti Dinar", code: "KWD", symbol: "ك.د" },
  { name: "Kyrgystani Som", code: "KGS", symbol: "лв" },
  { name: "Laotian Kip", code: "LAK", symbol: "₭" },
  { name: "Latvian Lats", code: "LVL", symbol: "Ls" },
  { name: "Lebanese Pound", code: "LBP", symbol: "£" },
  { name: "Lesotho Loti", code: "LSL", symbol: "L" },
  { name: "Liberian Dollar", code: "LRD", symbol: "$" },
  { name: "Libyan Dinar", code: "LYD", symbol: "د.ل" },
  { name: "Litecoin", code: "LTC", symbol: "Ł" },
  { name: "Lithuanian Litas", code: "LTL", symbol: "Lt" },
  { name: "Macanese Pataca", code: "MOP", symbol: "$" },
  { name: "Macedonian Denar", code: "MKD", symbol: "ден" },
  { name: "Malagasy Ariary", code: "MGA", symbol: "Ar" },
  { name: "Malawian Kwacha", code: "MWK", symbol: "MK" },
  { name: "Malaysian Ringgit", code: "MYR", symbol: "RM" },
  { name: "Maldivian Rufiyaa", code: "MVR", symbol: "Rf" },
  { name: "Mauritanian Ouguiya", code: "MRO", symbol: "MRU" },
  { name: "Mauritian Rupee", code: "MUR", symbol: "₨" },
  { name: "Mexican Peso", code: "MXN", symbol: "$" },
  { name: "Moldovan Leu", code: "MDL", symbol: "L" },
  { name: "Mongolian Tugrik", code: "MNT", symbol: "₮" },
  { name: "Moroccan Dirham", code: "MAD", symbol: "MAD" },
  { name: "Mozambican Metical", code: "MZM", symbol: "MT" },
  { name: "Myanmar Kyat", code: "MMK", symbol: "K" },
  { name: "Namibian Dollar", code: "NAD", symbol: "$" },
  { name: "Nepalese Rupee", code: "NPR", symbol: "₨" },
  { name: "Netherlands Antillean Guilder", code: "ANG", symbol: "ƒ" },
  { name: "New Taiwan Dollar", code: "TWD", symbol: "$" },
  { name: "New Zealand Dollar", code: "NZD", symbol: "$" },
  { name: "Nicaraguan Córdoba", code: "NIO", symbol: "C$" },
  { name: "Nigerian Naira", code: "NGN", symbol: "₦" },
  { name: "North Korean Won", code: "KPW", symbol: "₩" },
  { name: "Norwegian Krone", code: "NOK", symbol: "kr" },
  { name: "Omani Rial", code: "OMR", symbol: ".ع.ر" },
  { name: "Pakistani Rupee", code: "PKR", symbol: "₨" },
  { name: "Panamanian Balboa", code: "PAB", symbol: "B/." },
  { name: "Papua New Guinean Kina", code: "PGK", symbol: "K" },
  { name: "Paraguayan Guarani", code: "PYG", symbol: "₲" },
  { name: "Peruvian Nuevo Sol", code: "PEN", symbol: "S/." },
  { name: "Philippine Peso", code: "PHP", symbol: "₱" },
  { name: "Polish Zloty", code: "PLN", symbol: "zł" },
  { name: "Qatari Rial", code: "QAR", symbol: "ق.ر" },
  { name: "Romanian Leu", code: "RON", symbol: "lei" },
  { name: "Russian Ruble", code: "RUB", symbol: "₽" },
  { name: "Rwandan Franc", code: "RWF", symbol: "FRw" },
  { name: "Salvadoran Colón", code: "SVC", symbol: "₡" },
  { name: "Samoan Tala", code: "WST", symbol: "SAT" },
  { name: "São Tomé and Príncipe Dobra", code: "STD", symbol: "Db" },
  { name: "Saudi Riyal", code: "SAR", symbol: "﷼" },
  { name: "Serbian Dinar", code: "RSD", symbol: "din" },
  { name: "Seychellois Rupee", code: "SCR", symbol: "SRe" },
  { name: "Sierra Leonean Leone", code: "SLL", symbol: "Le" },
  { name: "Singapore Dollar", code: "SGD", symbol: "$" },
  { name: "Slovak Koruna", code: "SKK", symbol: "Sk" },
  { name: "Solomon Islands Dollar", code: "SBD", symbol: "Si$" },
  { name: "Somali Shilling", code: "SOS", symbol: "Sh.so." },
  { name: "South African Rand", code: "ZAR", symbol: "R" },
  { name: "South Korean Won", code: "KRW", symbol: "₩" },
  { name: "South Sudanese Pound", code: "SSP", symbol: "£" },
  { name: "Special Drawing Rights", code: "XDR", symbol: "SDR" },
  { name: "Sri Lankan Rupee", code: "LKR", symbol: "Rs" },
  { name: "St. Helena Pound", code: "SHP", symbol: "£" },
  { name: "Sudanese Pound", code: "SDG", symbol: ".س.ج" },
  { name: "Surinamese Dollar", code: "SRD", symbol: "$" },
  { name: "Swazi Lilangeni", code: "SZL", symbol: "E" },
  { name: "Swedish Krona", code: "SEK", symbol: "kr" },
  { name: "Swiss Franc", code: "CHF", symbol: "CHf" },
  { name: "Syrian Pound", code: "SYP", symbol: "LS" },
  { name: "Tajikistani Somoni", code: "TJS", symbol: "SM" },
  { name: "Tanzanian Shilling", code: "TZS", symbol: "TSh" },
  { name: "Thai Baht", code: "THB", symbol: "฿" },
  { name: "Tongan Pa'anga", code: "TOP", symbol: "$" },
  { name: "Trinidad & Tobago Dollar", code: "TTD", symbol: "$" },
  { name: "Tunisian Dinar", code: "TND", symbol: "ت.د" },
  { name: "Turkish Lira", code: "TRY", symbol: "₺" },
  { name: "Turkmenistani Manat", code: "TMT", symbol: "T" },
  { name: "Ugandan Shilling", code: "UGX", symbol: "USh" },
  { name: "Ukrainian Hryvnia", code: "UAH", symbol: "₴" },
  { name: "United Arab Emirates Dirham", code: "AED", symbol: "إ.د" },
  { name: "Uruguayan Peso", code: "UYU", symbol: "$" },
  { name: "US Dollar", code: "USD", symbol: "$" },
  { name: "Uzbekistan Som", code: "UZS", symbol: "лв" },
  { name: "Vanuatu Vatu", code: "VUV", symbol: "VT" },
  { name: "Venezuelan BolÃvar", code: "VEF", symbol: "Bs" },
  { name: "Vietnamese Dong", code: "VND", symbol: "₫" },
  { name: "Yemeni Rial", code: "YER", symbol: "﷼" },
  { name: "Zambian Kwacha", code: "ZMK", symbol: "ZK" },
  { name: "Zimbabwean dollar", code: "ZWL", symbol: "$" },
];

export const country_list = [
  { name: "Afghanistan", code: "AF" },
  { name: "land Islands", code: "AX" },
  { name: "Albania", code: "AL" },
  { name: "Algeria", code: "DZ" },
  { name: "American Samoa", code: "AS" },
  { name: "AndorrA", code: "AD" },
  { name: "Angola", code: "AO" },
  { name: "Anguilla", code: "AI" },
  { name: "Antarctica", code: "AQ" },
  { name: "Antigua and Barbuda", code: "AG" },
  { name: "Argentina", code: "AR" },
  { name: "Armenia", code: "AM" },
  { name: "Aruba", code: "AW" },
  { name: "Australia", code: "AU" },
  { name: "Austria", code: "AT" },
  { name: "Azerbaijan", code: "AZ" },
  { name: "Bahamas", code: "BS" },
  { name: "Bahrain", code: "BH" },
  { name: "Bangladesh", code: "BD" },
  { name: "Barbados", code: "BB" },
  { name: "Belarus", code: "BY" },
  { name: "Belgium", code: "BE" },
  { name: "Belize", code: "BZ" },
  { name: "Benin", code: "BJ" },
  { name: "Bermuda", code: "BM" },
  { name: "Bhutan", code: "BT" },
  { name: "Bolivia", code: "BO" },
  { name: "Bosnia and Herzegovina", code: "BA" },
  { name: "Botswana", code: "BW" },
  { name: "Bouvet Island", code: "BV" },
  { name: "Brazil", code: "BR" },
  { name: "British Indian Ocean Territory", code: "IO" },
  { name: "Brunei Darussalam", code: "BN" },
  { name: "Bulgaria", code: "BG" },
  { name: "Burkina Faso", code: "BF" },
  { name: "Burundi", code: "BI" },
  { name: "Cambodia", code: "KH" },
  { name: "Cameroon", code: "CM" },
  { name: "Canada", code: "CA" },
  { name: "Cape Verde", code: "CV" },
  { name: "Cayman Islands", code: "KY" },
  { name: "Central African Republic", code: "CF" },
  { name: "Chad", code: "TD" },
  { name: "Chile", code: "CL" },
  { name: "China", code: "CN" },
  { name: "Christmas Island", code: "CX" },
  { name: "Cocos (Keeling) Islands", code: "CC" },
  { name: "Colombia", code: "CO" },
  { name: "Comoros", code: "KM" },
  { name: "Congo", code: "CG" },
  { name: "Congo, The Democratic Republic of the", code: "CD" },
  { name: "Cook Islands", code: "CK" },
  { name: "Costa Rica", code: "CR" },
  { name: "Cote D'Ivoire", code: "CI" },
  { name: "Croatia", code: "HR" },
  { name: "Cuba", code: "CU" },
  { name: "Cyprus", code: "CY" },
  { name: "Czech Republic", code: "CZ" },
  { name: "Denmark", code: "DK" },
  { name: "Djibouti", code: "DJ" },
  { name: "Dominica", code: "DM" },
  { name: "Dominican Republic", code: "DO" },
  { name: "Ecuador", code: "EC" },
  { name: "Egypt", code: "EG" },
  { name: "El Salvador", code: "SV" },
  { name: "Equatorial Guinea", code: "GQ" },
  { name: "Eritrea", code: "ER" },
  { name: "Estonia", code: "EE" },
  { name: "Ethiopia", code: "ET" },
  { name: "Falkland Islands (Malvinas)", code: "FK" },
  { name: "Faroe Islands", code: "FO" },
  { name: "Fiji", code: "FJ" },
  { name: "Finland", code: "FI" },
  { name: "France", code: "FR" },
  { name: "French Guiana", code: "GF" },
  { name: "French Polynesia", code: "PF" },
  { name: "French Southern Territories", code: "TF" },
  { name: "Gabon", code: "GA" },
  { name: "Gambia", code: "GM" },
  { name: "Georgia", code: "GE" },
  { name: "Germany", code: "DE" },
  { name: "Ghana", code: "GH" },
  { name: "Gibraltar", code: "GI" },
  { name: "Greece", code: "GR" },
  { name: "Greenland", code: "GL" },
  { name: "Grenada", code: "GD" },
  { name: "Guadeloupe", code: "GP" },
  { name: "Guam", code: "GU" },
  { name: "Guatemala", code: "GT" },
  { name: "Guernsey", code: "GG" },
  { name: "Guinea", code: "GN" },
  { name: "Guinea-Bissau", code: "GW" },
  { name: "Guyana", code: "GY" },
  { name: "Haiti", code: "HT" },
  { name: "Heard Island and Mcdonald Islands", code: "HM" },
  { name: "Holy See (Vatican City State)", code: "VA" },
  { name: "Honduras", code: "HN" },
  { name: "Hong Kong", code: "HK" },
  { name: "Hungary", code: "HU" },
  { name: "Iceland", code: "IS" },
  { name: "India", code: "IN" },
  { name: "Indonesia", code: "ID" },
  { name: "Iran, Islamic Republic Of", code: "IR" },
  { name: "Iraq", code: "IQ" },
  { name: "Ireland", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "Israel", code: "IL" },
  { name: "Italy", code: "IT" },
  { name: "Jamaica", code: "JM" },
  { name: "Japan", code: "JP" },
  { name: "Jersey", code: "JE" },
  { name: "Jordan", code: "JO" },
  { name: "Kazakhstan", code: "KZ" },
  { name: "Kenya", code: "KE" },
  { name: "Kiribati", code: "KI" },
  { name: "Korea, Democratic PeopleS Republic of", code: "KP" },
  { name: "Korea, Republic of", code: "KR" },
  { name: "Kuwait", code: "KW" },
  { name: "Kyrgyzstan", code: "KG" },
  { name: "Lao People'S Democratic Republic", code: "LA" },
  { name: "Latvia", code: "LV" },
  { name: "Lebanon", code: "LB" },
  { name: "Lesotho", code: "LS" },
  { name: "Liberia", code: "LR" },
  { name: "Libyan Arab Jamahiriya", code: "LY" },
  { name: "Liechtenstein", code: "LI" },
  { name: "Lithuania", code: "LT" },
  { name: "Luxembourg", code: "LU" },
  { name: "Macao", code: "MO" },
  { name: "Macedonia, The Former Yugoslav Republic of", code: "MK" },
  { name: "Madagascar", code: "MG" },
  { name: "Malawi", code: "MW" },
  { name: "Malaysia", code: "MY" },
  { name: "Maldives", code: "MV" },
  { name: "Mali", code: "ML" },
  { name: "Malta", code: "MT" },
  { name: "Marshall Islands", code: "MH" },
  { name: "Martinique", code: "MQ" },
  { name: "Mauritania", code: "MR" },
  { name: "Mauritius", code: "MU" },
  { name: "Mayotte", code: "YT" },
  { name: "Mexico", code: "MX" },
  { name: "Micronesia, Federated States of", code: "FM" },
  { name: "Moldova, Republic of", code: "MD" },
  { name: "Monaco", code: "MC" },
  { name: "Mongolia", code: "MN" },
  { name: "Montenegro", code: "ME" },
  { name: "Montserrat", code: "MS" },
  { name: "Morocco", code: "MA" },
  { name: "Mozambique", code: "MZ" },
  { name: "Myanmar", code: "MM" },
  { name: "Namibia", code: "NA" },
  { name: "Nauru", code: "NR" },
  { name: "Nepal", code: "NP" },
  { name: "Netherlands", code: "NL" },
  { name: "Netherlands Antilles", code: "AN" },
  { name: "New Caledonia", code: "NC" },
  { name: "New Zealand", code: "NZ" },
  { name: "Nicaragua", code: "NI" },
  { name: "Niger", code: "NE" },
  { name: "Nigeria", code: "NG" },
  { name: "Niue", code: "NU" },
  { name: "Norfolk Island", code: "NF" },
  { name: "Northern Mariana Islands", code: "MP" },
  { name: "Norway", code: "NO" },
  { name: "Oman", code: "OM" },
  { name: "Pakistan", code: "PK" },
  { name: "Palau", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "Panama", code: "PA" },
  { name: "Papua New Guinea", code: "PG" },
  { name: "Paraguay", code: "PY" },
  { name: "Peru", code: "PE" },
  { name: "Philippines", code: "PH" },
  { name: "Pitcairn", code: "PN" },
  { name: "Poland", code: "PL" },
  { name: "Portugal", code: "PT" },
  { name: "Puerto Rico", code: "PR" },
  { name: "Qatar", code: "QA" },
  { name: "Reunion", code: "RE" },
  { name: "Romania", code: "RO" },
  { name: "Russian Federation", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "Saint Helena", code: "SH" },
  { name: "Saint Kitts and Nevis", code: "KN" },
  { name: "Saint Lucia", code: "LC" },
  { name: "Saint Pierre and Miquelon", code: "PM" },
  { name: "Saint Vincent and the Grenadines", code: "VC" },
  { name: "Samoa", code: "WS" },
  { name: "San Marino", code: "SM" },
  { name: "Sao Tome and Principe", code: "ST" },
  { name: "Saudi Arabia", code: "SA" },
  { name: "Senegal", code: "SN" },
  { name: "Serbia", code: "RS" },
  { name: "Seychelles", code: "SC" },
  { name: "Sierra Leone", code: "SL" },
  { name: "Singapore", code: "SG" },
  { name: "Slovakia", code: "SK" },
  { name: "Slovenia", code: "SI" },
  { name: "Solomon Islands", code: "SB" },
  { name: "Somalia", code: "SO" },
  { name: "South Africa", code: "ZA" },
  { name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { name: "Spain", code: "ES" },
  { name: "Sri Lanka", code: "LK" },
  { name: "Sudan", code: "SD" },
  { name: "Suriname", code: "SR" },
  { name: "Svalbard and Jan Mayen", code: "SJ" },
  { name: "Swaziland", code: "SZ" },
  { name: "Sweden", code: "SE" },
  { name: "Switzerland", code: "CH" },
  { name: "Syrian Arab Republic", code: "SY" },
  { name: "Taiwan, Province of China", code: "TW" },
  { name: "Tajikistan", code: "TJ" },
  { name: "Tanzania, United Republic of", code: "TZ" },
  { name: "Thailand", code: "TH" },
  { name: "Timor-Leste", code: "TL" },
  { name: "Togo", code: "TG" },
  { name: "Tokelau", code: "TK" },
  { name: "Tonga", code: "TO" },
  { name: "Trinidad and Tobago", code: "TT" },
  { name: "Tunisia", code: "TN" },
  { name: "Turkey", code: "TR" },
  { name: "Turkmenistan", code: "TM" },
  { name: "Turks and Caicos Islands", code: "TC" },
  { name: "Tuvalu", code: "TV" },
  { name: "Uganda", code: "UG" },
  { name: "Ukraine", code: "UA" },
  { name: "United Arab Emirates", code: "AE" },
  { name: "United Kingdom", code: "GB" },
  { name: "United States", code: "US" },
  { name: "United States Minor Outlying Islands", code: "UM" },
  { name: "Uruguay", code: "UY" },
  { name: "Uzbekistan", code: "UZ" },
  { name: "Vanuatu", code: "VU" },
  { name: "Venezuela", code: "VE" },
  { name: "Viet Nam", code: "VN" },
  { name: "Virgin Islands, British", code: "VG" },
  { name: "Virgin Islands, U.S.", code: "VI" },
  { name: "Wallis and Futuna", code: "WF" },
  { name: "Western Sahara", code: "EH" },
  { name: "Yemen", code: "YE" },
  { name: "Zambia", code: "ZM" },
  { name: "Zimbabwe", code: "ZW" },
];

export const job_titles = [
  "Academic Librarian",
  "Accountant",
  "Accounting Technician",
  "Actuary",
  "Adult Nurse",
  "Advertising Account executive",
  "Advertising Account planner",
  "Advertising Copywriter",
  "Advice Worker",
  "Aeronautical Engineer",
  "Agricultural Consultant",
  "Agricultural Manager",
  "Aid Worker/Humanitarian Worker",
  "Air Traffic Controller",
  "Airline Cabin Crew",
  "Amenity Horticulturist",
  "Analytical Chemist",
  "Animal Nutritionist",
  "Animator",
  "Archaeologist",
  "Architect",
  "Architectural Technologist",
  "Archivist",
  "Armed Forces Officer",
  "AromaTherapist",
  "Art Therapist",
  "Arts Administrator",
  "Auditor",
  "Automotive Engineer",
  "Barrister",
  "Barrister's Clerk",
  "Bid Manager",
  "Bilingual Secretary",
  "Biomedical Engineer",
  "Biomedical Scientist",
  "Biotechnologist",
  "Border Force Officer",
  "Brand Manager",
  "Broadcasting Presenter",
  "Building Control Officer/Surveyor",
  "Building Services Engineer",
  "Building Surveyor",
  "Business Analyst",
  "Camera Operator",
  "Careers Adviser (Higher Education)",
  "Careers Adviser",
  "Careers Consultant",
  "Cartographer",
  "Catering Manager",
  "CEO",
  "Charities Administrator",
  "Charities Fundraiser",
  "Chemical (Process) Engineer",
  "Child PsychoTherapist",
  "Children's Nurse",
  "Chiropractor",
  "Civil Engineer",
  "Civil Service Administrator",
  "Clinical Biochemist",
  "Clinical Cytogeneticist",
  "Clinical Microbiologist",
  "Clinical Molecular Geneticist",
  "Clinical Research Associate",
  "Clinical Scientist",
  "Clothing Technologist",
  "Colour Technologist",
  "Commercial Airline Pilot",
  "Commercial Horticulturist",
  "Commercial/Residential Surveyor",
  "Commissioning Editor",
  "Commissioning Engineer",
  "Commodity Broker",
  "Communications Engineer",
  "Community Arts Worker",
  "Community Education Officer",
  "Community Worker",
  "Company Secretary",
  "Computer Sales Support",
  "Computer Scientist",
  "Conference Organiser",
  "Consultant",
  "Consumer Rights Adviser",
  "Control and Instrumentation Engineer",
  "Corporate Banker",
  "Corporate Treasurer",
  "Counsellor",
  "Court Reporter/Verbatim Reporter",
  "Credit Analyst",
  "Crown Prosecution Service lawyer",
  "Crystallographer",
  "Curator",
  "Customs Officer",
  "Cyber Security Specialist",
  "Dance Movement PsychoTherapist",
  "Data Analyst",
  "Data Scientist",
  "Data Visualisation Analyst",
  "Database Administrator",
  "Debt/Dinance Adviser",
  "Dental Hygienist",
  "Dentist",
  "Design Engineer",
  "Design Manager (Construction)",
  "DevOps Engineer",
  "Dietitian",
  "Diplomatic Service",
  "Doctor (GP)",
  "Doctor (Hospital)",
  "DramaTherapist",
  "Economist",
  "Editorial Assistant",
  "Education Administrator",
  "Electrical Engineer",
  "Electronics Engineer",
  "Employment Advice Worker",
  "Energy Conservation Officer",
  "Energy Consultant",
  "Engineering Geologist",
  "Environmental Education Officer",
  "Environmental Health Officer",
  "Environmental Manager",
  "Environmental Scientist",
  "Equal Opportunities Officer",
  "Equality and Diversity Officer",
  "Ergonomist",
  "Estate Agent",
  "Estimator",
  "European Commission Administrators",
  "Executive Director",
  "Exhibition Display Designer",
  "Exhibition Organiser",
  "Exploration Geologist",
  "Facilities Manager",
  "Field Trials Officer",
  "Financial Manager",
  "Fire Engineer",
  "Firefighter",
  "Fisheries Enforcement Officer",
  "Fitness Centre Manager",
  "Food Scientist",
  "Food Technologist",
  "Forensic Scientist",
  "Freight Forwarder",
  "Geneticist",
  "Geographical Information Systems Manager",
  "Geomatics/Land Surveyor",
  "Government Lawyer",
  "Government Research Officer",
  "Graphic Designer",
  "Health and Safety Adviser",
  "Health and Safety Inspector",
  "Health Promotion Specialist",
  "Health Service Manager",
  "Health Visitor",
  "Herbalist",
  "Heritage Manager",
  "Higher Education Administrator",
  "Higher Education Advice Worker",
  "Homeless Support Worker",
  "Horticultural Consultant",
  "Hotel Manager",
  "Housing Adviser",
  "Human Resources Officer",
  "Hydrologist",
  "Illustrator",
  "Immigration Officer",
  "Immunologist",
  "Industrial/Product Designer",
  "Information Scientist",
  "Information Systems Manager",
  "Information Technology/Software Trainers",
  "Insurance Broker",
  "Insurance Claims Inspector",
  "Insurance Risk Surveyor",
  "Insurance Underwriter",
  "Interpreter",
  "Investment Analyst",
  "Investment Banker - Corporate Finance",
  "Investment Banker - Operations",
  "Investment FUnd Manager",
  "IT Consultant",
  "IT Support Analyst",
  "Journalist",
  "Laboratory Technician",
  "Land-based Engineer",
  "Landscape Architect",
  "Learning Disability Nurse",
  "Learning Mentor",
  "Lecturer (Adult Education)",
  "Lecturer (Further Education)",
  "Lecturer (Higher Education)",
  "Legal Executive",
  "Leisure Centre Manager",
  "Licensed Conveyancer",
  "Local Government administrator",
  "Local Government lawyer",
  "Logistics/Distribution Manager",
  "Magazine Features Editor",
  "Magazine Journalist",
  "Maintenance Engineer",
  "Management accountant",
  "Manufacturing Engineer",
  "Manufacturing Machine Operator",
  "Manufacturing Toolmaker",
  "Marine Scientist",
  "Market Research Analyst",
  "Market Research Executive",
  "Marketing Assistant",
  "Marketing Executive",
  "Marketing Manager (Direct)",
  "Marketing Manager (Social Media)",
  "Materials Engineer",
  "Materials Specialist",
  "Mechanical Engineer",
  "Media Analyst",
  "Media Buyer",
  "Media Planner",
  "Medical Physicist",
  "Medical Representative",
  "Mental Health Nurse",
  "Metallurgist",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Mining Engineer",
  "Mobile Developer",
  "Multimedia Programmer",
  "Multimedia Specialists",
  "Museum Education Officer",
  "Museum/Gallery Exhibition Officer",
  "Music Therapist",
  "Nanoscientist",
  "Nature Conservation Officer",
  "Naval Architect",
  "Network Administrator",
  "Nurse",
  "Nutritional Therapist",
  "Nutritionist",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Operational Researcher",
  "Orthoptist",
  "Outdoor Pursuits Manager",
  "Packaging Technologist",
  "Paramedic",
  "Patent Attorney",
  "Patent Examiner",
  "Pension Scheme Manager",
  "Personal Assistant",
  "Petroleum Engineer",
  "Pharmacist",
  "Pharmacologist",
  "Pharmacovigilance Officer",
  "Photographer",
  "PhysioTherapist",
  "Picture Researcher",
  "Planning and Development Surveyor",
  "Planning Technician",
  "Plant Breeder",
  "Police Officer",
  "Political Party Agent",
  "Political Researcher",
  "Practice nurse",
  "Press Photographer",
  "Press Sub-editor",
  "Prison Officer",
  "Private Music Teacher",
  "Probation Officer",
  "Product Development Scientist",
  "Production Manager",
  "Programme Researcher",
  "Project Manager",
  "Psychologist (Clinical)",
  "Psychologist (Educational)",
  "PsychoTherapist",
  "Public Affairs Consultant (Lobbyist)",
  "Public Affairs Consultant (Research)",
  "Public House Manager",
  "Public Librarian",
  "Public Relations (PR) Officer",
  "QA Analyst",
  "Quality Assurance Manager",
  "Quantity Surveyor",
  "Records Manager",
  "Recruitment Consultant",
  "Recycling Officer",
  "Regulatory Affairs Officer",
  "Research Chemist",
  "Research Scientist",
  "Restaurant Manager",
  "Retail Banker",
  "Retail Buyer",
  "Retail Manager",
  "Retail Merchandiser",
  "Retail Pharmacist",
  "Sales Executive",
  "Scene of Crime Officer",
  "Secretary",
  "Seismic Interpreter",
  "Site Engineer",
  "Site Manager",
  "Social Researcher",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Soil Scientist",
  "Solicitor",
  "Speech and Language Therapist",
  "Sports Coach",
  "Sports Development Officer",
  "Sports Therapist",
  "Statistician",
  "Stockbroker",
  "Structural Engineer",
  "Systems Analyst",
  "Systems Developer",
  "Tax Inspector",
  "Teacher (Nursery Years)",
  "Teacher (Primary)",
  "Teacher (Secondary)",
  "Teacher (Special Educational Needs)",
  "Teaching/Classroom Assistant",
  "Technical Author",
  "Technical Sales Engineer",
  "TEFL/TESL Teacher",
  "Television Production Assistant",
  "Test Automation Developer",
  "Tour Guide",
  "Tour Operator",
  "Tour/Holiday Representative",
  "Tourism Officer",
  "Tourist Information Manager",
  "Town and Country Planner",
  "Toxicologist",
  "Trade Union Official",
  "Trade Union Research Officer",
  "Trader",
  "Trading Standards Officer",
  "Training and Development Officer",
  "Translator",
  "Transportation Planner",
  "Travel Agent",
  "TV/Film/Theatre Set Designer",
  "UX Designer",
  "Validation Engineer",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Video Game Designer",
  "Video Game Developer",
  "Volunteer Work Organiser",
  "Waste Management Officer",
  "Water Conservation Officer",
  "Water Engineer",
  "Web Designer",
  "Web Developer",
  "Welfare Rights Adviser",
  "Writer",
  "Youth Worker",
];
